"""OpenAI LLM implementation."""

from openai import OpenAI

from ..core.exceptions import LLMError
from ..models.article import Article
from .base import BaseLLM


DEFAULT_SUMMARY_PROMPT = """You are a professional news analyst specializing in artificial intelligence and technology.

Analyze the following news articles and create a comprehensive weekly report. Your report should:

1. **Executive Summary**: A brief overview of the week's most important developments (2-3 paragraphs)

2. **Key Developments**: Group related articles by topic and summarize the main points:
   - Highlight breakthrough technologies or significant announcements
   - Note important company updates or product launches
   - Identify emerging trends or patterns

3. **Industry Impact**: Analyze how these developments might affect:
   - The AI/tech industry
   - Related sectors
   - Society and end users

4. **Trends to Watch**: Identify 3-5 ongoing trends based on the news coverage

Format the report in clean markdown with clear sections and bullet points.
Include source references where relevant.

Here are the articles to analyze:

{articles}
"""


class OpenAILLM(BaseLLM):
    """OpenAI LLM provider."""

    def __init__(
        self,
        api_key: str,
        model: str = "gpt-4o",
        max_tokens: int = 4096,
        temperature: float = 0.3,
    ):
        """Initialize OpenAI LLM.

        Args:
            api_key: OpenAI API key.
            model: Model to use.
            max_tokens: Maximum tokens in response.
            temperature: Sampling temperature.
        """
        if not api_key:
            raise LLMError("OpenAI API key is required")

        self._client = OpenAI(api_key=api_key)
        self._model = model
        self._max_tokens = max_tokens
        self._temperature = temperature

    @property
    def provider_name(self) -> str:
        return "OpenAI"

    async def summarize(self, articles: list[Article], prompt: str | None = None) -> str:
        """Generate a summary using OpenAI.

        Args:
            articles: List of articles to summarize.
            prompt: Optional custom prompt.

        Returns:
            Generated summary.
        """
        if not articles:
            return "No articles to summarize."

        context = self._format_articles_for_context(articles)
        full_prompt = (prompt or DEFAULT_SUMMARY_PROMPT).format(articles=context)

        try:
            response = self._client.chat.completions.create(
                model=self._model,
                max_tokens=self._max_tokens,
                temperature=self._temperature,
                messages=[{"role": "user", "content": full_prompt}],
            )
            return response.choices[0].message.content or ""

        except Exception as e:
            raise LLMError(f"OpenAI API error: {e}") from e

    async def generate_report(
        self,
        articles: list[Article],
        title: str,
        prompt: str | None = None,
    ) -> str:
        """Generate a full report using OpenAI.

        Args:
            articles: List of articles.
            title: Report title.
            prompt: Optional custom prompt.

        Returns:
            Generated report in markdown.
        """
        summary = await self.summarize(articles, prompt)

        report = f"""# {title}

*Generated by AI News Reporter using {self.provider_name}*

---

{summary}

---

## Sources

"""
        for article in articles:
            report += f"- [{article.title}]({article.url}) - {article.source}\n"

        return report
